cmake_minimum_required(VERSION 3.22.1)
project(m2bootstrap LANGUAGES C CXX)
add_library(m2bootstrap SHARED bootstrap.cpp recomp_runtime.cpp)
find_library(log-lib log)
find_library(dl-lib dl)
find_library(vulkan-lib vulkan)
target_compile_features(m2bootstrap PRIVATE cxx_std_20)
target_compile_options(m2bootstrap PRIVATE -Wall -Wextra -Wpedantic)
target_link_libraries(m2bootstrap PRIVATE ${log-lib} ${dl-lib} ${vulkan-lib})
